version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - 'POSTGRES_DB=market'
      - 'POSTGRES_PASSWORD=alda121086'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - rede
    volumes:
      - /home/filipe/data/postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
    environment:
      TZ: America/Sao_Paulo
      spring.datasource.url: jdbc:postgresql://db:5432/market?createDatabaseIfNotExist=true&&useSSL=false&&useTimezone=true&&serverTimezone=UTC
      spring.datasource.username: postgres
      spring.datasource.password: alda121086
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - rede

networks:
  rede:
    driver: bridge